# Site settings
title: Sydney Interactive Arts Meetup
email: mark@markcmitchell.net
description: > # this means to ignore newlines until next key.
  A meetup in Sydney for Interactive Artists. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: sydney_iam
github_username:  sydneyinteractivearts
exclude: [bower_components, node_modules, gulpfile.js]

sass:
  style: compressed

# Build settings
markdown: kramdown
